import {ChangeDetectionStrategy, Component, ViewEncapsulation} from '@angular/core';
import { FontAwesomeIconsRegistry, } from '@triangular/font-awesome-icons';

import {
  fontAwesomeIconTable,
  fontAwesomeIconTablet,
  fontAwesomeIconTablets,
  fontAwesomeIconTag,
  fontAwesomeIconTags,
  fontAwesomeIconTape,
  fontAwesomeIconTaxi,
  fontAwesomeIconTeamspeak,
  fontAwesomeIconTeethOpen,
  fontAwesomeIconTeeth,
  fontAwesomeIconTelegram,
  fontAwesomeIconTemperatureHigh,
  fontAwesomeIconTemperatureLow,
  fontAwesomeIconTencentWeibo,
  fontAwesomeIconTerminal,
  fontAwesomeIconTextHeight,
  fontAwesomeIconTextWidth,
  fontAwesomeIconTheRedYeti,
  fontAwesomeIconThemeco,
  fontAwesomeIconThemeisle,
  fontAwesomeIconThermometer,
  fontAwesomeIconThinkPeaks,
  fontAwesomeIconThumbsDown,
  fontAwesomeIconThumbsUp,
  fontAwesomeIconThumbtack,
  fontAwesomeIconToggleOff,
  fontAwesomeIconToggleOn,
  fontAwesomeIconToiletPaperSlash,
  fontAwesomeIconToiletPaper,
  fontAwesomeIconToilet,
  fontAwesomeIconToolbox,
  fontAwesomeIconTooth,
  fontAwesomeIconToriiGate,
  fontAwesomeIconTractor,
  fontAwesomeIconTradeFederation,
  fontAwesomeIconTrademark,
  fontAwesomeIconTrafficLight,
  fontAwesomeIconTrailer,
  fontAwesomeIconTrain,
  fontAwesomeIconTransgender,
  fontAwesomeIconTrash,
  fontAwesomeIconTree,
  fontAwesomeIconTrello,
  fontAwesomeIconTrophy,
  fontAwesomeIconTruckMonster,
  fontAwesomeIconTruckMoving,
  fontAwesomeIconTruckPickup,
  fontAwesomeIconTruck,
  fontAwesomeIconTty,
  fontAwesomeIconTumblrSquare,
  fontAwesomeIconTumblr,
  fontAwesomeIconTv,
  fontAwesomeIconTwitch,
  fontAwesomeIconTwitterSquare,
  fontAwesomeIconTwitter,
  fontAwesomeIconTypo3,
} from '@triangular/font-awesome-icons/icons';

@Component({
  selector: 'app-icons-t',
  templateUrl: './icons-t.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: false // eslint-disable-line @angular-eslint/prefer-standalone
})
export class IconsTComponent {
  icons = [
    fontAwesomeIconTable,
    fontAwesomeIconTablet,
    fontAwesomeIconTablets,
    fontAwesomeIconTag,
    fontAwesomeIconTags,
    fontAwesomeIconTape,
    fontAwesomeIconTaxi,
    fontAwesomeIconTeamspeak,
    fontAwesomeIconTeethOpen,
    fontAwesomeIconTeeth,
    fontAwesomeIconTelegram,
    fontAwesomeIconTemperatureHigh,
    fontAwesomeIconTemperatureLow,
    fontAwesomeIconTencentWeibo,
    fontAwesomeIconTerminal,
    fontAwesomeIconTextHeight,
    fontAwesomeIconTextWidth,
    fontAwesomeIconTheRedYeti,
    fontAwesomeIconThemeco,
    fontAwesomeIconThemeisle,
    fontAwesomeIconThermometer,
    fontAwesomeIconThinkPeaks,
    fontAwesomeIconThumbsDown,
    fontAwesomeIconThumbsUp,
    fontAwesomeIconThumbtack,
    fontAwesomeIconToggleOff,
    fontAwesomeIconToggleOn,
    fontAwesomeIconToiletPaperSlash,
    fontAwesomeIconToiletPaper,
    fontAwesomeIconToilet,
    fontAwesomeIconToolbox,
    fontAwesomeIconTooth,
    fontAwesomeIconToriiGate,
    fontAwesomeIconTractor,
    fontAwesomeIconTradeFederation,
    fontAwesomeIconTrademark,
    fontAwesomeIconTrafficLight,
    fontAwesomeIconTrailer,
    fontAwesomeIconTrain,
    fontAwesomeIconTransgender,
    fontAwesomeIconTrash,
    fontAwesomeIconTree,
    fontAwesomeIconTrello,
    fontAwesomeIconTrophy,
    fontAwesomeIconTruckMonster,
    fontAwesomeIconTruckMoving,
    fontAwesomeIconTruckPickup,
    fontAwesomeIconTruck,
    fontAwesomeIconTty,
    fontAwesomeIconTumblrSquare,
    fontAwesomeIconTumblr,
    fontAwesomeIconTv,
    fontAwesomeIconTwitch,
    fontAwesomeIconTwitterSquare,
    fontAwesomeIconTwitter,
    fontAwesomeIconTypo3,
  ];

  constructor(private registry: FontAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
