import { Component, ViewEncapsulation } from '@angular/core';
import { FontAwesomeIconsRegistry, } from '@triangular/font-awesome-icons';

import {
  fontAwesomeIconDAndDBeyond,
  fontAwesomeIconDAndD,
  fontAwesomeIconDailymotion,
  fontAwesomeIconDashcube,
  fontAwesomeIconDatabase,
  fontAwesomeIconDeaf,
  fontAwesomeIconDelicious,
  fontAwesomeIconDemocrat,
  fontAwesomeIconDeploydog,
  fontAwesomeIconDeskpro,
  fontAwesomeIconDesktop,
  fontAwesomeIconDev,
  fontAwesomeIconDeviantart,
  fontAwesomeIconDharmachakra,
  fontAwesomeIconDhl,
  fontAwesomeIconDiagnoses,
  fontAwesomeIconDiaspora,
  fontAwesomeIconDiceD20,
  fontAwesomeIconDiceD6,
  fontAwesomeIconDiceFive,
  fontAwesomeIconDiceFour,
  fontAwesomeIconDiceOne,
  fontAwesomeIconDiceSix,
  fontAwesomeIconDiceThree,
  fontAwesomeIconDiceTwo,
  fontAwesomeIconDice,
  fontAwesomeIconDigg,
  fontAwesomeIconDigitalOcean,
  fontAwesomeIconDigitalTachograph,
  fontAwesomeIconDirections,
  fontAwesomeIconDiscord,
  fontAwesomeIconDiscourse,
  fontAwesomeIconDisease,
  fontAwesomeIconDivide,
  fontAwesomeIconDizzy,
  fontAwesomeIconDna,
  fontAwesomeIconDochub,
  fontAwesomeIconDocker,
  fontAwesomeIconDog,
  fontAwesomeIconDollarSign,
  fontAwesomeIconDollyFlatbed,
  fontAwesomeIconDolly,
  fontAwesomeIconDonate,
  fontAwesomeIconDoorClosed,
  fontAwesomeIconDoorOpen,
  fontAwesomeIconDotCircle,
  fontAwesomeIconDove,
  fontAwesomeIconDownload,
  fontAwesomeIconDraft2Digital,
  fontAwesomeIconDraftingCompass,
  fontAwesomeIconDragon,
  fontAwesomeIconDrawPolygon,
  fontAwesomeIconDribbbleSquare,
  fontAwesomeIconDribbble,
  fontAwesomeIconDropbox,
  fontAwesomeIconDrumSteelpan,
  fontAwesomeIconDrum,
  fontAwesomeIconDrumstickBite,
  fontAwesomeIconDrupal,
  fontAwesomeIconDumbbell,
  fontAwesomeIconDumpsterFire,
  fontAwesomeIconDumpster,
  fontAwesomeIconDungeon,
  fontAwesomeIconDyalog,
} from '@triangular/font-awesome-icons/icons';

@Component({
  selector: 'app-icons-d',
  templateUrl: './icons-d.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
})
export class IconsDComponent {
  icons = [
    fontAwesomeIconDAndDBeyond,
    fontAwesomeIconDAndD,
    fontAwesomeIconDailymotion,
    fontAwesomeIconDashcube,
    fontAwesomeIconDatabase,
    fontAwesomeIconDeaf,
    fontAwesomeIconDelicious,
    fontAwesomeIconDemocrat,
    fontAwesomeIconDeploydog,
    fontAwesomeIconDeskpro,
    fontAwesomeIconDesktop,
    fontAwesomeIconDev,
    fontAwesomeIconDeviantart,
    fontAwesomeIconDharmachakra,
    fontAwesomeIconDhl,
    fontAwesomeIconDiagnoses,
    fontAwesomeIconDiaspora,
    fontAwesomeIconDiceD20,
    fontAwesomeIconDiceD6,
    fontAwesomeIconDiceFive,
    fontAwesomeIconDiceFour,
    fontAwesomeIconDiceOne,
    fontAwesomeIconDiceSix,
    fontAwesomeIconDiceThree,
    fontAwesomeIconDiceTwo,
    fontAwesomeIconDice,
    fontAwesomeIconDigg,
    fontAwesomeIconDigitalOcean,
    fontAwesomeIconDigitalTachograph,
    fontAwesomeIconDirections,
    fontAwesomeIconDiscord,
    fontAwesomeIconDiscourse,
    fontAwesomeIconDisease,
    fontAwesomeIconDivide,
    fontAwesomeIconDizzy,
    fontAwesomeIconDna,
    fontAwesomeIconDochub,
    fontAwesomeIconDocker,
    fontAwesomeIconDog,
    fontAwesomeIconDollarSign,
    fontAwesomeIconDollyFlatbed,
    fontAwesomeIconDolly,
    fontAwesomeIconDonate,
    fontAwesomeIconDoorClosed,
    fontAwesomeIconDoorOpen,
    fontAwesomeIconDotCircle,
    fontAwesomeIconDove,
    fontAwesomeIconDownload,
    fontAwesomeIconDraft2Digital,
    fontAwesomeIconDraftingCompass,
    fontAwesomeIconDragon,
    fontAwesomeIconDrawPolygon,
    fontAwesomeIconDribbbleSquare,
    fontAwesomeIconDribbble,
    fontAwesomeIconDropbox,
    fontAwesomeIconDrumSteelpan,
    fontAwesomeIconDrum,
    fontAwesomeIconDrumstickBite,
    fontAwesomeIconDrupal,
    fontAwesomeIconDumbbell,
    fontAwesomeIconDumpsterFire,
    fontAwesomeIconDumpster,
    fontAwesomeIconDungeon,
    fontAwesomeIconDyalog,
  ];

  constructor(private registry: FontAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
