import {ChangeDetectionStrategy, Component, ViewEncapsulation} from '@angular/core';
import { FontAwesomeIconsRegistry, } from '@triangular/font-awesome-icons';

import {
  fontAwesomeIconGalacticRepublic,
  fontAwesomeIconGalacticSenate,
  fontAwesomeIconGamepad,
  fontAwesomeIconGasPump,
  fontAwesomeIconGavel,
  fontAwesomeIconGem,
  fontAwesomeIconGenderless,
  fontAwesomeIconGetPocket,
  fontAwesomeIconGgCircle,
  fontAwesomeIconGg,
  fontAwesomeIconGhost,
  fontAwesomeIconGift,
  fontAwesomeIconGifts,
  fontAwesomeIconGitAlt,
  fontAwesomeIconGitSquare,
  fontAwesomeIconGit,
  fontAwesomeIconGithubAlt,
  fontAwesomeIconGithubSquare,
  fontAwesomeIconGithub,
  fontAwesomeIconGitkraken,
  fontAwesomeIconGitlab,
  fontAwesomeIconGitter,
  fontAwesomeIconGlasses,
  fontAwesomeIconGlideG,
  fontAwesomeIconGlide,
  fontAwesomeIconGlobe,
  fontAwesomeIconGofore,
  fontAwesomeIconGoodreadsG,
  fontAwesomeIconGoodreads,
  fontAwesomeIconGoogleDrive,
  fontAwesomeIconGooglePlay,
  fontAwesomeIconGooglePlusG,
  fontAwesomeIconGooglePlusSquare,
  fontAwesomeIconGooglePlus,
  fontAwesomeIconGoogleWallet,
  fontAwesomeIconGoogle,
  fontAwesomeIconGopuram,
  fontAwesomeIconGraduationCap,
  fontAwesomeIconGratipay,
  fontAwesomeIconGrav,
  fontAwesomeIconGreaterThanEqual,
  fontAwesomeIconGreaterThan,
  fontAwesomeIconGripLinesVertical,
  fontAwesomeIconGripLines,
  fontAwesomeIconGripVertical,
  fontAwesomeIconGripfire,
  fontAwesomeIconGrunt,
  fontAwesomeIconGuitar,
  fontAwesomeIconGulp,
} from '@triangular/font-awesome-icons/icons';

// eslint-disable-next-line @angular-eslint/prefer-standalone
@Component({
  selector: 'app-icons-g',
  templateUrl: './icons-g.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: false
})
export class IconsGComponent {
  icons = [
    fontAwesomeIconGalacticRepublic,
    fontAwesomeIconGalacticSenate,
    fontAwesomeIconGamepad,
    fontAwesomeIconGasPump,
    fontAwesomeIconGavel,
    fontAwesomeIconGem,
    fontAwesomeIconGenderless,
    fontAwesomeIconGetPocket,
    fontAwesomeIconGgCircle,
    fontAwesomeIconGg,
    fontAwesomeIconGhost,
    fontAwesomeIconGift,
    fontAwesomeIconGifts,
    fontAwesomeIconGitAlt,
    fontAwesomeIconGitSquare,
    fontAwesomeIconGit,
    fontAwesomeIconGithubAlt,
    fontAwesomeIconGithubSquare,
    fontAwesomeIconGithub,
    fontAwesomeIconGitkraken,
    fontAwesomeIconGitlab,
    fontAwesomeIconGitter,
    fontAwesomeIconGlasses,
    fontAwesomeIconGlideG,
    fontAwesomeIconGlide,
    fontAwesomeIconGlobe,
    fontAwesomeIconGofore,
    fontAwesomeIconGoodreadsG,
    fontAwesomeIconGoodreads,
    fontAwesomeIconGoogleDrive,
    fontAwesomeIconGooglePlay,
    fontAwesomeIconGooglePlusG,
    fontAwesomeIconGooglePlusSquare,
    fontAwesomeIconGooglePlus,
    fontAwesomeIconGoogleWallet,
    fontAwesomeIconGoogle,
    fontAwesomeIconGopuram,
    fontAwesomeIconGraduationCap,
    fontAwesomeIconGratipay,
    fontAwesomeIconGrav,
    fontAwesomeIconGreaterThanEqual,
    fontAwesomeIconGreaterThan,
    fontAwesomeIconGripLinesVertical,
    fontAwesomeIconGripLines,
    fontAwesomeIconGripVertical,
    fontAwesomeIconGripfire,
    fontAwesomeIconGrunt,
    fontAwesomeIconGuitar,
    fontAwesomeIconGulp,
  ];

  constructor(private registry: FontAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
