import { Component, ViewEncapsulation } from '@angular/core';
import { FontAwesomeIconsRegistry, } from '@triangular/font-awesome-icons';

import {
  fontAwesomeIconLandmark,
  fontAwesomeIconLanguage,
  fontAwesomeIconLaptopCode,
  fontAwesomeIconLaptopHouse,
  fontAwesomeIconLaptopMedical,
  fontAwesomeIconLaptop,
  fontAwesomeIconLaravel,
  fontAwesomeIconLastfmSquare,
  fontAwesomeIconLastfm,
  fontAwesomeIconLaughBeam,
  fontAwesomeIconLaughSquint,
  fontAwesomeIconLaughWink,
  fontAwesomeIconLaugh,
  fontAwesomeIconLayerGroup,
  fontAwesomeIconLeaf,
  fontAwesomeIconLeanpub,
  fontAwesomeIconLemon,
  fontAwesomeIconLessThanEqual,
  fontAwesomeIconLessThan,
  fontAwesomeIconLess,
  fontAwesomeIconLevelDownAlt,
  fontAwesomeIconLevelUpAlt,
  fontAwesomeIconLifeRing,
  fontAwesomeIconLightbulb,
  fontAwesomeIconLine,
  fontAwesomeIconLink,
  fontAwesomeIconLinkedinIn,
  fontAwesomeIconLinkedin,
  fontAwesomeIconLinode,
  fontAwesomeIconLinux,
  fontAwesomeIconLiraSign,
  fontAwesomeIconListAlt,
  fontAwesomeIconListOl,
  fontAwesomeIconListUl,
  fontAwesomeIconList,
  fontAwesomeIconLocationArrow,
  fontAwesomeIconLockOpen,
  fontAwesomeIconLock,
  fontAwesomeIconLongArrowAltDown,
  fontAwesomeIconLongArrowAltLeft,
  fontAwesomeIconLongArrowAltRight,
  fontAwesomeIconLongArrowAltUp,
  fontAwesomeIconLowVision,
  fontAwesomeIconLuggageCart,
  fontAwesomeIconLungsVirus,
  fontAwesomeIconLungs,
  fontAwesomeIconLyft,
} from '@triangular/font-awesome-icons/icons';

@Component({
  selector: 'app-icons-l',
  templateUrl: './icons-l.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
})
export class IconsLComponent {
  icons = [
    fontAwesomeIconLandmark,
    fontAwesomeIconLanguage,
    fontAwesomeIconLaptopCode,
    fontAwesomeIconLaptopHouse,
    fontAwesomeIconLaptopMedical,
    fontAwesomeIconLaptop,
    fontAwesomeIconLaravel,
    fontAwesomeIconLastfmSquare,
    fontAwesomeIconLastfm,
    fontAwesomeIconLaughBeam,
    fontAwesomeIconLaughSquint,
    fontAwesomeIconLaughWink,
    fontAwesomeIconLaugh,
    fontAwesomeIconLayerGroup,
    fontAwesomeIconLeaf,
    fontAwesomeIconLeanpub,
    fontAwesomeIconLemon,
    fontAwesomeIconLessThanEqual,
    fontAwesomeIconLessThan,
    fontAwesomeIconLess,
    fontAwesomeIconLevelDownAlt,
    fontAwesomeIconLevelUpAlt,
    fontAwesomeIconLifeRing,
    fontAwesomeIconLightbulb,
    fontAwesomeIconLine,
    fontAwesomeIconLink,
    fontAwesomeIconLinkedinIn,
    fontAwesomeIconLinkedin,
    fontAwesomeIconLinode,
    fontAwesomeIconLinux,
    fontAwesomeIconLiraSign,
    fontAwesomeIconListAlt,
    fontAwesomeIconListOl,
    fontAwesomeIconListUl,
    fontAwesomeIconList,
    fontAwesomeIconLocationArrow,
    fontAwesomeIconLockOpen,
    fontAwesomeIconLock,
    fontAwesomeIconLongArrowAltDown,
    fontAwesomeIconLongArrowAltLeft,
    fontAwesomeIconLongArrowAltRight,
    fontAwesomeIconLongArrowAltUp,
    fontAwesomeIconLowVision,
    fontAwesomeIconLuggageCart,
    fontAwesomeIconLungsVirus,
    fontAwesomeIconLungs,
    fontAwesomeIconLyft,
  ];

  constructor(private registry: FontAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
