import {ChangeDetectionStrategy, Component, ViewEncapsulation} from '@angular/core';
import { FontAwesomeIconsRegistry, } from '@triangular/font-awesome-icons';

import {
  fontAwesomeIconRProject,
  fontAwesomeIconRadiation,
  fontAwesomeIconRainbow,
  fontAwesomeIconRaspberryPi,
  fontAwesomeIconRavelry,
  fontAwesomeIconReact,
  fontAwesomeIconReacteurope,
  fontAwesomeIconReadme,
  fontAwesomeIconRebel,
  fontAwesomeIconReceipt,
  fontAwesomeIconRecordVinyl,
  fontAwesomeIconRecycle,
  fontAwesomeIconRedRiver,
  fontAwesomeIconRedditAlien,
  fontAwesomeIconRedditSquare,
  fontAwesomeIconReddit,
  fontAwesomeIconRedhat,
  fontAwesomeIconRegistered,
  fontAwesomeIconRenren,
  fontAwesomeIconReplyAll,
  fontAwesomeIconReply,
  fontAwesomeIconReplyd,
  fontAwesomeIconRepublican,
  fontAwesomeIconResearchgate,
  fontAwesomeIconResolving,
  fontAwesomeIconRestroom,
  fontAwesomeIconRetweet,
  fontAwesomeIconRev,
  fontAwesomeIconRibbon,
  fontAwesomeIconRing,
  fontAwesomeIconRoad,
  fontAwesomeIconRobot,
  fontAwesomeIconRocket,
  fontAwesomeIconRocketchat,
  fontAwesomeIconRockrms,
  fontAwesomeIconRoute,
  fontAwesomeIconRss,
  fontAwesomeIconRubleSign,
  fontAwesomeIconRulerCombined,
  fontAwesomeIconRulerHorizontal,
  fontAwesomeIconRulerVertical,
  fontAwesomeIconRuler,
  fontAwesomeIconRupeeSign,
} from '@triangular/font-awesome-icons/icons';

@Component({
  selector: 'app-icons-r',
  templateUrl: './icons-r.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: false // eslint-disable-line @angular-eslint/prefer-standalone
})
export class IconsRComponent {
  icons = [
    fontAwesomeIconRProject,
    fontAwesomeIconRadiation,
    fontAwesomeIconRainbow,
    fontAwesomeIconRaspberryPi,
    fontAwesomeIconRavelry,
    fontAwesomeIconReact,
    fontAwesomeIconReacteurope,
    fontAwesomeIconReadme,
    fontAwesomeIconRebel,
    fontAwesomeIconReceipt,
    fontAwesomeIconRecordVinyl,
    fontAwesomeIconRecycle,
    fontAwesomeIconRedRiver,
    fontAwesomeIconRedditAlien,
    fontAwesomeIconRedditSquare,
    fontAwesomeIconReddit,
    fontAwesomeIconRedhat,
    fontAwesomeIconRegistered,
    fontAwesomeIconRenren,
    fontAwesomeIconReplyAll,
    fontAwesomeIconReply,
    fontAwesomeIconReplyd,
    fontAwesomeIconRepublican,
    fontAwesomeIconResearchgate,
    fontAwesomeIconResolving,
    fontAwesomeIconRestroom,
    fontAwesomeIconRetweet,
    fontAwesomeIconRev,
    fontAwesomeIconRibbon,
    fontAwesomeIconRing,
    fontAwesomeIconRoad,
    fontAwesomeIconRobot,
    fontAwesomeIconRocket,
    fontAwesomeIconRocketchat,
    fontAwesomeIconRockrms,
    fontAwesomeIconRoute,
    fontAwesomeIconRss,
    fontAwesomeIconRubleSign,
    fontAwesomeIconRulerCombined,
    fontAwesomeIconRulerHorizontal,
    fontAwesomeIconRulerVertical,
    fontAwesomeIconRuler,
    fontAwesomeIconRupeeSign,
  ];

  constructor(private registry: FontAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
