import { Component, ViewEncapsulation } from '@angular/core';
import { FontAwesomeIconsRegistry, } from '@triangular/font-awesome-icons';

import {
  fontAwesomeIconUber,
  fontAwesomeIconUbuntu,
  fontAwesomeIconUikit,
  fontAwesomeIconUmbraco,
  fontAwesomeIconUmbrellaBeach,
  fontAwesomeIconUmbrella,
  fontAwesomeIconUnderline,
  fontAwesomeIconUndoAlt,
  fontAwesomeIconUndo,
  fontAwesomeIconUniregistry,
  fontAwesomeIconUnity,
  fontAwesomeIconUniversalAccess,
  fontAwesomeIconUniversity,
  fontAwesomeIconUnlink,
  fontAwesomeIconUnlockAlt,
  fontAwesomeIconUnlock,
  fontAwesomeIconUntappd,
  fontAwesomeIconUpload,
  fontAwesomeIconUps,
  fontAwesomeIconUsb,
  fontAwesomeIconUserAltSlash,
  fontAwesomeIconUserAlt,
  fontAwesomeIconUserAstronaut,
  fontAwesomeIconUserCheck,
  fontAwesomeIconUserCircle,
  fontAwesomeIconUserClock,
  fontAwesomeIconUserCog,
  fontAwesomeIconUserEdit,
  fontAwesomeIconUserFriends,
  fontAwesomeIconUserGraduate,
  fontAwesomeIconUserInjured,
  fontAwesomeIconUserLock,
  fontAwesomeIconUserMd,
  fontAwesomeIconUserMinus,
  fontAwesomeIconUserNinja,
  fontAwesomeIconUserNurse,
  fontAwesomeIconUserPlus,
  fontAwesomeIconUserSecret,
  fontAwesomeIconUserShield,
  fontAwesomeIconUserSlash,
  fontAwesomeIconUserTag,
  fontAwesomeIconUserTie,
  fontAwesomeIconUserTimes,
  fontAwesomeIconUser,
  fontAwesomeIconUsersCog,
  fontAwesomeIconUsers,
  fontAwesomeIconUsps,
  fontAwesomeIconUssunnah,
  fontAwesomeIconUtensilSpoon,
  fontAwesomeIconUtensils,
} from '@triangular/font-awesome-icons/icons';

@Component({
  selector: 'app-icons-u',
  templateUrl: './icons-u.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
})
export class IconsUComponent {
  icons = [
    fontAwesomeIconUber,
    fontAwesomeIconUbuntu,
    fontAwesomeIconUikit,
    fontAwesomeIconUmbraco,
    fontAwesomeIconUmbrellaBeach,
    fontAwesomeIconUmbrella,
    fontAwesomeIconUnderline,
    fontAwesomeIconUndoAlt,
    fontAwesomeIconUndo,
    fontAwesomeIconUniregistry,
    fontAwesomeIconUnity,
    fontAwesomeIconUniversalAccess,
    fontAwesomeIconUniversity,
    fontAwesomeIconUnlink,
    fontAwesomeIconUnlockAlt,
    fontAwesomeIconUnlock,
    fontAwesomeIconUntappd,
    fontAwesomeIconUpload,
    fontAwesomeIconUps,
    fontAwesomeIconUsb,
    fontAwesomeIconUserAltSlash,
    fontAwesomeIconUserAlt,
    fontAwesomeIconUserAstronaut,
    fontAwesomeIconUserCheck,
    fontAwesomeIconUserCircle,
    fontAwesomeIconUserClock,
    fontAwesomeIconUserCog,
    fontAwesomeIconUserEdit,
    fontAwesomeIconUserFriends,
    fontAwesomeIconUserGraduate,
    fontAwesomeIconUserInjured,
    fontAwesomeIconUserLock,
    fontAwesomeIconUserMd,
    fontAwesomeIconUserMinus,
    fontAwesomeIconUserNinja,
    fontAwesomeIconUserNurse,
    fontAwesomeIconUserPlus,
    fontAwesomeIconUserSecret,
    fontAwesomeIconUserShield,
    fontAwesomeIconUserSlash,
    fontAwesomeIconUserTag,
    fontAwesomeIconUserTie,
    fontAwesomeIconUserTimes,
    fontAwesomeIconUser,
    fontAwesomeIconUsersCog,
    fontAwesomeIconUsers,
    fontAwesomeIconUsps,
    fontAwesomeIconUssunnah,
    fontAwesomeIconUtensilSpoon,
    fontAwesomeIconUtensils,
  ];

  constructor(private registry: FontAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
