import { ChangeDetectionStrategy, Component, ViewEncapsulation, inject } from '@angular/core';
import { FontAwesomeIconsRegistry, } from '@triangular/font-awesome-icons';

import {
  fontAwesomeIconFacebookF,
  fontAwesomeIconFacebookMessenger,
  fontAwesomeIconFacebookSquare,
  fontAwesomeIconFacebook,
  fontAwesomeIconFan,
  fontAwesomeIconFantasyFlightGames,
  fontAwesomeIconFaucet,
  fontAwesomeIconFax,
  fontAwesomeIconFeather,
  fontAwesomeIconFedex,
  fontAwesomeIconFedora,
  fontAwesomeIconFigma,
  fontAwesomeIconFileAudio,
  fontAwesomeIconFileCode,
  fontAwesomeIconFileContract,
  fontAwesomeIconFileCsv,
  fontAwesomeIconFileExcel,
  fontAwesomeIconFileExport,
  fontAwesomeIconFileImage,
  fontAwesomeIconFileImport,
  fontAwesomeIconFileInvoiceDollar,
  fontAwesomeIconFileInvoice,
  fontAwesomeIconFileMedical,
  fontAwesomeIconFilePdf,
  fontAwesomeIconFilePowerpoint,
  fontAwesomeIconFilePrescription,
  fontAwesomeIconFileSignature,
  fontAwesomeIconFileVideo,
  fontAwesomeIconFileWord,
  fontAwesomeIconFile,
  fontAwesomeIconFillDrip,
  fontAwesomeIconFill,
  fontAwesomeIconFilm,
  fontAwesomeIconFilter,
  fontAwesomeIconFingerprint,
  fontAwesomeIconFireExtinguisher,
  fontAwesomeIconFire,
  fontAwesomeIconFirefoxBrowser,
  fontAwesomeIconFirefox,
  fontAwesomeIconFirstOrderAlt,
  fontAwesomeIconFirstOrder,
  fontAwesomeIconFirstdraft,
  fontAwesomeIconFish,
  fontAwesomeIconFlagCheckered,
  fontAwesomeIconFlagUsa,
  fontAwesomeIconFlag,
  fontAwesomeIconFlask,
  fontAwesomeIconFlickr,
  fontAwesomeIconFlipboard,
  fontAwesomeIconFly,
  fontAwesomeIconFolderMinus,
  fontAwesomeIconFolderOpen,
  fontAwesomeIconFolderPlus,
  fontAwesomeIconFolder,
  fontAwesomeIconFont,
  fontAwesomeIconFonticonsFi,
  fontAwesomeIconFonticons,
  fontAwesomeIconFortAwesomeAlt,
  fontAwesomeIconFortAwesome,
  fontAwesomeIconForumbee,
  fontAwesomeIconForward,
  fontAwesomeIconFoursquare,
  fontAwesomeIconFreeCodeCamp,
  fontAwesomeIconFreebsd,
  fontAwesomeIconFrog,
  fontAwesomeIconFulcrum,
  fontAwesomeIconFutbol,
} from '@triangular/font-awesome-icons/icons';

@Component({
  selector: 'app-icons-f',
  templateUrl: './icons-f.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: false // eslint-disable-line @angular-eslint/prefer-standalone
})
export class IconsFComponent {
  private registry = inject(FontAwesomeIconsRegistry);

  icons = [
    fontAwesomeIconFacebookF,
    fontAwesomeIconFacebookMessenger,
    fontAwesomeIconFacebookSquare,
    fontAwesomeIconFacebook,
    fontAwesomeIconFan,
    fontAwesomeIconFantasyFlightGames,
    fontAwesomeIconFaucet,
    fontAwesomeIconFax,
    fontAwesomeIconFeather,
    fontAwesomeIconFedex,
    fontAwesomeIconFedora,
    fontAwesomeIconFigma,
    fontAwesomeIconFileAudio,
    fontAwesomeIconFileCode,
    fontAwesomeIconFileContract,
    fontAwesomeIconFileCsv,
    fontAwesomeIconFileExcel,
    fontAwesomeIconFileExport,
    fontAwesomeIconFileImage,
    fontAwesomeIconFileImport,
    fontAwesomeIconFileInvoiceDollar,
    fontAwesomeIconFileInvoice,
    fontAwesomeIconFileMedical,
    fontAwesomeIconFilePdf,
    fontAwesomeIconFilePowerpoint,
    fontAwesomeIconFilePrescription,
    fontAwesomeIconFileSignature,
    fontAwesomeIconFileVideo,
    fontAwesomeIconFileWord,
    fontAwesomeIconFile,
    fontAwesomeIconFillDrip,
    fontAwesomeIconFill,
    fontAwesomeIconFilm,
    fontAwesomeIconFilter,
    fontAwesomeIconFingerprint,
    fontAwesomeIconFireExtinguisher,
    fontAwesomeIconFire,
    fontAwesomeIconFirefoxBrowser,
    fontAwesomeIconFirefox,
    fontAwesomeIconFirstOrderAlt,
    fontAwesomeIconFirstOrder,
    fontAwesomeIconFirstdraft,
    fontAwesomeIconFish,
    fontAwesomeIconFlagCheckered,
    fontAwesomeIconFlagUsa,
    fontAwesomeIconFlag,
    fontAwesomeIconFlask,
    fontAwesomeIconFlickr,
    fontAwesomeIconFlipboard,
    fontAwesomeIconFly,
    fontAwesomeIconFolderMinus,
    fontAwesomeIconFolderOpen,
    fontAwesomeIconFolderPlus,
    fontAwesomeIconFolder,
    fontAwesomeIconFont,
    fontAwesomeIconFonticonsFi,
    fontAwesomeIconFonticons,
    fontAwesomeIconFortAwesomeAlt,
    fontAwesomeIconFortAwesome,
    fontAwesomeIconForumbee,
    fontAwesomeIconForward,
    fontAwesomeIconFoursquare,
    fontAwesomeIconFreeCodeCamp,
    fontAwesomeIconFreebsd,
    fontAwesomeIconFrog,
    fontAwesomeIconFulcrum,
    fontAwesomeIconFutbol,
  ];

  constructor() {
    const registry = this.registry;

    registry.registerIcons(this.icons);
  }

}
